### ISSUE TITLE
Invalid VRID throws error when it does not exist on device

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#117]
Using the default_vrid setting, if you specify a VRID not yet created on the device, the create call bombs.  Is this a situation where we want to create said VRID if it does not exist for a more seamless UX?

**Comment by Cedev** [comment]
We don't have enough information to create a VRID. For a meaningful VRID we'd need one or more floating ips (used for the NAT pool), priorities, and monitors and their priority costs.

There are basically two setups that use VRIDs: a failover pair that uses a single VRID or a chassis with multiple blades that uses `N*(N-1)` VRIDs where `N` is the number of blades in the chassis. A setting for a single default vrid supports the failover pair. In either case, the VRIDs, their priorities, monitors, and priority costs need to be configured.
