### ISSUE TITLE
Where is properly a10 driver for kilo and liberty?

### ISSUE THREAD

**Issue by sasukeh** [a10networks/a10-neutron-lbaas#123]
I just want to integrate a10 lb to openstack **kilo** and **liberty** release.
According to readme.md, There is only driver for juno release.

I have three question for you guys...
1) How about the progress of the work for kilo and liberty?
2) I think only Issue of github has those information of a10 driver, right?
3) Is there some useful information to integrate a10LB to OpenStack in other place **except github**?

**Comment by Cedev** [comment]
Using the current driver with **kilo** has, for the most, been tested. To get the latest stable release `sudo pip install a10-neutron-lbaas`. Follow the installation instructions from [https://github.com/a10networks/a10-neutron-lbaas](https://github.com/a10networks/a10-neutron-lbaas). There are a few newer features (auto souce nat, ip-in-ip, and vrid) mentioned in the installation instructions that are only in the 1.3.6 version from github and aren't yet in the stable 1.3.5 version you'll get from [pypi](https://pypi.python.org/pypi/a10-neutron-lbaas/1.3.5) when you install the driver from `pip`.

**Comment by sasukeh** [comment]
Cedev
Thank you for your comment. I will use a10-neutron-lbaas of stable version 1.3.5 from pypi repos.
