### ISSUE TITLE
Python 2.6 is being abandoned

### ISSUE THREAD

**Issue by Cedev** [a10networks/a10-neutron-lbaas#130]
Python 2.6 support is being dropped from openstack. As of Juno, openstack requires python 2.7. We're still trying to support Icehouse, which could optionally run with 2.6.

The first problem we've encountered is a dictionary comprehension is oslo messaging, which causes our `py26` tests to fail. Oslo messaging is no longer tested against python 2.6. https://github.com/openstack/oslo.messaging/commit/2734fc8f505ca07ff1a4f4a420807e5c1b4ed812

We need to set upper bounds on the `requirements.txt` and `testrequirements.txt` for python 2.6. We can change the requirements for `py26` tests in `tox.ini`. I don't know how we can change the requirements for the library for python 2.6,

**Comment by Cedev** [comment]
The oslo messaging issue is resolved for now; the dictionary comprehension was removed in this revert: https://github.com/openstack/oslo.messaging/commit/468437454f16083dbd43eb6fd6daf6a3c98c15e0

**Comment by Cedev** [comment]
This is a non issue ... for now.

**Comment by Cedev** [comment]
And it's back

```
  File "/home/travis/build/a10networks/a10-neutron-lbaas/.tox/py26/lib/python2.6/site-packages/oslo_messaging/server.py", line 214
    self._states = {task: _OrderedTask(task) for task in self._tasks}
                                               ^
SyntaxError: invalid syntax
```

**Comment by mdurrant-b3** [comment]
As we no longer support py26 as a testing target, I see no reason to keep this open.  Closing.
