### ISSUE TITLE
Horizon a10 appliance UI improvements

### ISSUE THREAD

**Issue by Cedev** [a10networks/a10-neutron-lbaas#164]
As a horizon user, I want a polished UI experience when creating a10 images and instances

When creating a10 images:

 - [x] Add a visual distinction between the image source and the username, password so that a user doesn't think they're the credentials to download the image.
 - [x] Add explanation of what the username, password, and api version are for
 - [ ] Consider letting the user use an existing glance image instead of a url

When creating a10 instances:

 - [x] Use a password input for the password input
 - [ ] Filter list of images to only show a10 images. Will need to tag a10 images, which didn't work using v1/v2 client.

When listing a10 instances:

 - [ ] Filter list of instances to only show a10 instances. Will need to tag a10 instances or save 'em in a neutron service.

**Comment by mdurrant-b3** [comment]
Oddly, tags are being added to the image but the filter doesn't work.  The docs say the following structure is a valid filter:
```json
{"filters":
  "tag": "a10"
}
```
... but that filters returns all results.  I'd be happier to see if return zero results or blow up spectacularly if that filter is invalid.  At least then I know it's processing the filter.

**Comment by mdurrant-b3** [comment]
Using an existing glance image for an upload doesn't seem useful - the user will already have access to that image in the Launch Appliance screen.  Eventually, I see this screen evolving into something that hits a web service, authenticates using user creds, and allows the user to pull A10 images in "automagically".

**Comment by mdurrant-b3** [comment]
Regarding credentials for URLs... ugh.  Glance handles existing URLs not as gracefully as I'd like... how is it going to handle credentials?  I'm willing to find out, but am apprehensive.

**Comment by Cedev** [comment]
Don't worry about credentials for URLs. Just make it obvious that these *aren't* credentials for the URL. They are the credentials for api control of instances spun-up from the image.
