### ISSUE TITLE
Ensure correct auth url endpoint is being selected.

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#167]
Ran into a weird bug yesterday - we check for None in the auth token session variables and throw an exception if they're not there.  I don't think this is the correct approach and is related to expired sessions..

**Comment by mdurrant-b3** [comment]
It's not expired sessions - we're getting the wrong endpoint URL due to the non-deterministic method endpoints are retrieved from Keystone.  10 minute fix.

**Comment by mdurrant-b3** [comment]
Rolling this fix in to the one that involves creating the project under currently selected tenant (instead of currently logged in tenant) as they depend on each other.

**Comment by mdurrant-b3** [comment]
So it turns out this is an issue from Liberty -> Mitaka.  The shape of the endpoints changed - we put in some code to deal with the change in instance_manager.  Do we roll with this assuming everything is hunky-dory?

**Comment by Cedev** [comment]
Yeah, we roll with it. We don't have any reason to believe there's anything else to do.
