### ISSUE TITLE
Neutron a10-appliance-create commands should tell user acceptable argument values

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#180]
For protocol:
Using HTTPS, I got an error (I should get 'Unsupported protocol' or similar)
Using https, it worked fine.

**Comment by Cedev** [comment]
[RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.1)

> An implementation should accept uppercase letters as equivalent to lowercase in scheme names (e.g., allow "HTTP" as well as "http") for the sake of robustness but should only produce lowercase scheme names for consistency.
