### ISSUE TITLE
Add alembic to requirements.txt

### ISSUE THREAD

**Issue by Cedev** [a10networks/a10-neutron-lbaas#214]
Add `alembic>=0.8.0` to `requirements.txt`

> for the master trunk - it looks like the `a10-neutron-lbaas-db-manage` requires a specific version of alembic looks like > 0.8.0 and as such seems like its targeted towards liberty and newer?
> `>=**`
> would be nice if that requirement was done in requirements.txt or test-requirements.txt 
> As it needs: alembic.runtime.environment import `EnvironmentContext` which was added in 0.8.0 - are you guys expecting most of these deps to be satisfied by neutron?

Even if we were to rely on neutron satisfying dependencies, the use of `EnvironmentContext` in `cli.py` can't rely on Neutron having installed a specific version of `alembic`.

**Comment by dougwig** [comment]
no, i don't think we want this, or we have to have a branch for *every* openstack release. Does the stable/kilo and master split not cover this?

**Comment by dougwig** [comment]
Reworked to use older alembic.
