### ISSUE TITLE
Make sure we have length to store uuid/ip fields in member name

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#249]
On member name patch, switching from ip_neutron to uuid: 1) check if acos version have length restriction (I think <4.0 might), and 2) add this option to our driver, enabled by a config toggle.

**Comment by dougwig** [comment]
customer patch:
@@ -20,9 +20,10 @@
 class MemberHandler(handler_base_v1.HandlerBaseV1):
 
     def _get_name(self, member, ip_address):
-        tenant_label = member['tenant_id'][:5]
-        addr_label = str(ip_address).replace(".", "_", 4)
-        server_name = "_%s_%s_neutron" % (tenant_label, addr_label)
+        #tenant_label = member['tenant_id'][:5]
+        #addr_label = str(ip_address).replace(".", "_", 4)
+        #server_name = "_%s_%s_neutron" % (tenant_label, addr_label)
+        server_name = member['id']
         return server_name
