### ISSUE TITLE
A10_CONFIG_DIR ignored if /etc/a10/config.py exists

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#274]
As an a10-neutron-lbaas user, I would like A10_CONFIG_DIR to be the ultimate source of truth for where my configuration lives.

**Comment by mdurrant-b3** [comment]
@cedev @dougwig where did we end up on this?  Iirc the issue was the existence of /etc/a10/config.py causing the env var to get ignored.

**Comment by Cedev** [comment]
Here's where we ended up: https://github.com/a10networks/a10-neutron-lbaas/commit/728717055fcd59dffbbef69a7d4486ab6f9aff1a
