### ISSUE TITLE
add ipinip option to config file

### ISSUE THREAD

**Issue by dougwig** [a10networks/a10-neutron-lbaas#88]
For now, global boolean. If true, then in handle_listener,

add: 'ip_in_ip': True 

to the axapi_args vport dict.

And that axapi_args vport dict has a bug; it's currently 'port', which will never merge into the right dictionary in acos-client.

**Comment by mdurrant-b3** [comment]
If memory serves correct, it¹s port in one API version and vport in the
other.  I could be thinking of a different portion of the code, but I have a
distinct memory of port/vport transposition causing issues.

From:  dougwig <notifications@github.com>
Reply-To:  a10networks/a10-neutron-lbaas
<reply+0099686c58207d93325b499146276edf454027e93b91dce592cf00000001120adcf99
2a169ce06526b17@reply.github.com>
Date:  Friday, September 11, 2015 at 12:18 PM
To:  a10networks/a10-neutron-lbaas <a10-neutron-lbaas@noreply.github.com>
Subject:  [a10-neutron-lbaas] add ipinip option to config file (#88)

For now, global boolean. If true, then in handle_listener,

add: 'ip_in_ip': True

to the axapi_args vport dict.

And that axapi_args vport dict has a bug; it's currently 'port', which will
never merge into the right dictionary in acos-client.


Reply to this email directly or view it on GitHub
<https://github.com/a10networks/a10-neutron-lbaas/issues/88> .

**Comment by krislindgren** [comment]
The only way I could figure this out was to do it in the acos_client and modify: [1]

I tried modifying [2] to include ip_in_ip: True.  But that didn't work.  Audit log from the A10:
axapi: RemoteHost: 10.250.24.67:443 HTTP-Method: POST URI:
/services/rest/v2.1/format=json&method=slb.virtual_server.vport.create&session_
id=ac0996051700d985b7929638c7a4d8 Entity:
{"vport":{"status":1,"protocol":2,"name":"6f788efb-1b7b-4043-9703-
828392b0dcb4","port":96},"name":"ff03af86-5fbe-4666-b779-fc93a990ccde","port":{"
ip_in_ip":1}} Response: {"response": {"status": "OK"}} 

But when looking at the applied config - ip_in_ip was not added.

[1] - http://paste.ubuntu.com/12343245/
[2] - https://github.com/a10networks/a10-neutron-lbaas/blob/master/a10_neutron_lbaas/v2/handler_listener.py#L91

**Comment by mdurrant-b3** [comment]
This has been merged.
