### ISSUE TITLE
Non-existent config causes driver to crash

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#96]
If /etc/a10/config.py or other config paths don't exist (we should store these in a constant...) don't exist, the driver bombs and doesn't give enough info about said non-existence.
REPRODUCTION: Use v1 of the driver without creating a configuration.   Observe neato traceback.

**Comment by Cedev** [comment]
Already fixed in master (1.4.0) https://github.com/a10networks/a10-neutron-lbaas/pull/132/files#diff-a8c036a6e4d3d66c7e0f396657ca3246
